// src/lib/services/billing.service.ts
// ─────────────────────────────────────────────────────────────────────────────
// BILLING: The core operation this entire system was built for.
//
// TWO PUBLIC FUNCTIONS:
//
// lookupMemberByCard(cardNumber)
//   → finds card → member + wallet → computes readiness
//   → used by the billing UI before the cashier selects items
//
// createBill(input, actorId)
//   → THE ATOMIC BILLING OPERATION:
//   1. Validate inputs
//   2. Find card, member, wallet
//   3. Readiness gate (all 6 conditions must pass)
//   4. Fetch products + stock for all items
//   5. Build bill items with SNAPSHOT prices from DB
//   6. Verify balance sufficient + stock sufficient (pre-flight)
//   7. START TRANSACTION:
//      a. Create Bill document
//      b. Deduct wallet with $gte balance guard
//      c. Deduct stock per item with $gte qty guard
//      d. Create Transaction record
//      e. Create StockMovement per item
//   8. COMMIT
//
// If anything inside the transaction throws, ALL writes are rolled back.
//
// MODEL FIELD REFERENCE (what the actual Mongoose schemas use):
//   Stock:         currentQty         (NOT currentQuantity)
//   Transaction:   balanceBefore      (NOT walletBalanceBefore)
//                  balanceAfter       (NOT walletBalanceAfter)
//                  NO referenceId / referenceModel fields
//   StockMovement: movementType       (NOT type)
//                  quantityChanged    (NOT quantity)
//                  quantityBefore     (NOT balanceBefore)
//                  notes: string      (NOT null - must be string)
//   Bill:          subtotal on items  (NOT lineTotal)
//                  walletId required
//                  billNumber auto-generated by pre-save hook
// ─────────────────────────────────────────────────────────────────────────────

import mongoose, { type QueryFilter } from "mongoose";

import { startDbSession } from "@/lib/db";
import {
  BILL_STATUS,
  CARD_STATUS,
  RECORD_STATUS,
  STOCK_MOVEMENT_TYPES,
  TRANSACTION_TYPES,
} from "@/lib/constants";
import {
  Bill,
  Card,
  Member,
  Product,
  Stock,
  StockMovement,
  Transaction,
  Wallet,
  type ICard,
  type IBill,
  type IMember,
  type IWallet,
} from "@/lib/models";
import { AppError } from "@/types";

// ─── Output Types ──────────────────────────────────────────────────────────────

export interface BillLookupResult {
  member: {
    id: string;
    fullName: string;
    mobileNumber: string | null;
  };
  wallet: {
    id: string;
    currentBalance: number;
    status: string;
  };
  card: {
    id: string;
    cardNumber: string;
    status: string;
    expiresAt: string;
  };
  readiness: {
    isReady: boolean;
    checks: {
      memberActive:   boolean;
      walletExists:   boolean;
      walletActive:   boolean;
      cardAssigned:   boolean;
      cardActive:     boolean;
      cardNotExpired: boolean;
    };
  };
}

export interface BillItemRecord {
  productId:   string;
  productName: string;
  quantity:    number;
  unitPrice:   number;
  subtotal:    number;
}

export interface BillRecord {
  id:                  string;
  billNumber:          string;
  memberId:            string;
  memberName:          string;
  cardNumber:          string;
  cashierId:           string;
  items:               BillItemRecord[];
  totalAmount:         number;
  walletBalanceBefore: number;
  walletBalanceAfter:  number;
  createdAt:           string;
}

export interface BillListRecord {
  id:                  string;
  billNumber:          string;
  memberName:          string;
  cardNumber:          string;
  totalAmount:         number;
  itemCount:           number;
  walletBalanceBefore: number;
  walletBalanceAfter:  number;
  createdAt:           string;
}

// ─── computeReadiness ─────────────────────────────────────────────────────────
// Pure function - no side effects, no DB calls.
// Takes already-fetched Mongoose documents and evaluates each condition.
// wallet and card may be null if not yet assigned.
//
// Note: comparisons like (wallet !== null && wallet.status === "Active")
// already return boolean - no need for ?? false (which causes a TS warning
// because the comparison is never nullish).

export function computeReadiness(
  member: IMember,
  wallet: IWallet | null,
  card: ICard | null
): BillLookupResult["readiness"] {
  const now = new Date();

  const checks = {
    memberActive:   member.status === RECORD_STATUS.ACTIVE,
    walletExists:   wallet !== null,
    walletActive:   wallet !== null && wallet.status === RECORD_STATUS.ACTIVE,
    cardAssigned:   card !== null,
    cardActive:     card !== null && card.status === CARD_STATUS.ACTIVE,
    cardNotExpired: card !== null && new Date(card.expiresAt) > now,
  };

  const isReady = Object.values(checks).every(Boolean);
  return { isReady, checks };
}

// ─── lookupMemberByCard ───────────────────────────────────────────────────────
// Called when the cashier enters a card number.
// Returns full member + wallet + readiness before items are added.

export function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function buildCardNumberSearchPattern(cardNumber: string): RegExp {
  const normalized = cardNumber.trim().replace(/[\s-]+/g, "");
  const wildcard = normalized.split("").map(escapeRegExp).join("[\\s-]*");
  return new RegExp(wildcard, "i");
}

async function generateBillNumber(): Promise<string> {
  const date = new Date();
  const datePart =
    `${date.getFullYear()}` +
    `${String(date.getMonth() + 1).padStart(2, "0")}` +
    `${String(date.getDate()).padStart(2, "0")}`;

  for (let attempt = 0; attempt < 5; attempt++) {
    const random = Math.floor(Math.random() * 9000 + 1000).toString();
    const candidate = `BILL-${datePart}-${random}`;
    const existing = await Bill.findOne({ billNumber: candidate });
    if (!existing) return candidate;
  }

  throw new AppError("Could not generate a unique bill number. Please retry.", 500);
}

export async function lookupMemberByCard(
  cardNumber: string
): Promise<BillLookupResult> {
  if (!cardNumber?.trim()) {
    throw new AppError("Card number is required.", 400);
  }

  const card = await Card.findOne({
    cardNumber: buildCardNumberSearchPattern(cardNumber),
  }).sort({ createdAt: -1 });
  if (!card) throw new AppError("Card not found.", 404);

  const [member, wallet] = await Promise.all([
    Member.findOne({ _id: card.memberId, isDeleted: false }),
    Wallet.findOne({ memberId: card.memberId }),
  ]);

  if (!member) throw new AppError("Member not found.", 404);

  const readiness = computeReadiness(member, wallet, card);

  return {
    member: {
      id:           member._id.toString(),
      fullName:     member.fullName,
      mobileNumber: member.mobileNumber,
    },
    wallet: wallet
      ? {
          id:             wallet._id.toString(),
          currentBalance: wallet.currentBalance,
          status:         wallet.status,
        }
      : { id: "", currentBalance: 0, status: "Not found" },
    card: {
      id:         card._id.toString(),
      cardNumber: card.cardNumber,
      status:     card.status,
      expiresAt:  card.expiresAt.toISOString(),
    },
    readiness,
  };
}

// ─── createBill ───────────────────────────────────────────────────────────────
// THE MAIN ATOMIC BILLING OPERATION.
// Input:  cardNumber + array of { productId, quantity }
// Output: BillRecord with snapshot prices and wallet balance before/after

export async function createBill(
  input: {
    cardNumber?: string;
    items?: Array<{ productId: string; quantity: number }>;
  },
  actorId: string
): Promise<BillRecord> {
  // ── Step 1: Validate Inputs ────────────────────────────────────────────────

  if (!input.cardNumber?.trim()) {
    throw new AppError("Card number is required.", 400);
  }
  if (!input.items || !Array.isArray(input.items) || input.items.length === 0) {
    throw new AppError("At least one item is required.", 400);
  }
  for (const item of input.items) {
    if (!item.productId || !mongoose.Types.ObjectId.isValid(item.productId)) {
      throw new AppError("Invalid product ID in items.", 400);
    }
    if (!Number.isInteger(item.quantity) || item.quantity <= 0) {
      throw new AppError("Item quantities must be positive whole numbers.", 400);
    }
  }

  // ── Step 2: Find Card, Member, Wallet ──────────────────────────────────────

  const card = await Card.findOne({
    cardNumber: buildCardNumberSearchPattern(input.cardNumber),
  }).sort({ createdAt: -1 });
  if (!card) throw new AppError("Card not found.", 404);

  const [member, wallet] = await Promise.all([
    Member.findOne({ _id: card.memberId, isDeleted: false }),
    Wallet.findOne({ memberId: card.memberId }),
  ]);
  if (!member) throw new AppError("Member not found.", 404);
  if (!wallet) throw new AppError("Wallet not found for this member.", 404);

  // ── Step 3: Readiness Gate ─────────────────────────────────────────────────
  // All 6 conditions must be true. If any fail, billing is blocked with a
  // clear error message listing exactly which conditions failed.

  const readiness = computeReadiness(member, wallet, card);
  if (!readiness.isReady) {
    const failedChecks = Object.entries(readiness.checks)
      .filter(([, passed]) => !passed)
      .map(([key]) => key)
      .join(", ");
    throw new AppError(
      `Member is not ready for billing. Failed conditions: ${failedChecks}.`,
      400
    );
  }

  // ── Step 4: Fetch Products and Stock ──────────────────────────────────────
  // Fetch all at once using $in - no N+1 queries.

  const productIds = input.items.map(
    (i) => new mongoose.Types.ObjectId(i.productId)
  );

  const [products, stocks] = await Promise.all([
    Product.find({
      _id: { $in: productIds },
      isDeleted: false,
      status: RECORD_STATUS.ACTIVE,
    }),
    Stock.find({ productId: { $in: productIds } }),
  ]);

  if (products.length !== productIds.length) {
    throw new AppError("One or more products not found or inactive.", 400);
  }

  const productMap = new Map(products.map((p) => [p._id.toString(), p]));
  const stockMap   = new Map(stocks.map((s) => [s.productId.toString(), s]));

  // ── Step 5: Build Bill Items with Snapshot Prices ─────────────────────────
  // Prices come from the DB - never from the request body.
  // productName and unitPrice are snapshotted so historical bills remain
  // accurate even after prices change in the future.

  const billItems: Array<{
    productId:   mongoose.Types.ObjectId;
    productName: string;
    quantity:    number;
    unitPrice:   number;
    subtotal:    number;
  }> = [];

  for (const item of input.items) {
    const product = productMap.get(item.productId);
    if (!product) {
      throw new AppError(`Product not found: ${item.productId}`, 400);
    }

    const stock = stockMap.get(item.productId);
    if (!stock) {
      throw new AppError(
        `No stock record found for: ${product.productName}`,
        400
      );
    }

    // currentQty is the actual field name on the Stock model
    if (stock.currentQty < item.quantity) {
      throw new AppError(
        `Insufficient stock for "${product.productName}". Available: ${stock.currentQty}.`,
        400
      );
    }

    billItems.push({
      productId:   product._id,
      productName: product.productName,   // snapshot at billing time
      quantity:    item.quantity,
      unitPrice:   product.sellingPrice,  // snapshot at billing time
      subtotal:    item.quantity * product.sellingPrice,
    });
  }

  const totalAmount = billItems.reduce((sum, i) => sum + i.subtotal, 0);

  // ── Step 6: Pre-flight Balance Check ──────────────────────────────────────
  // The transaction also guards atomically, but checking here first gives a
  // clean error before any DB writes begin.

  if (wallet.currentBalance < totalAmount) {
    throw new AppError(
      `Insufficient wallet balance. ` +
      `Balance: ₹${wallet.currentBalance.toLocaleString("en-IN")}, ` +
      `Required: ₹${totalAmount.toLocaleString("en-IN")}.`,
      400
    );
  }

  const actorOid  = new mongoose.Types.ObjectId(actorId);
  const memberOid = member._id as mongoose.Types.ObjectId;
  const billNumber = await generateBillNumber();

  // ── Step 7: The Atomic Transaction ────────────────────────────────────────
  // All five document types are written inside one session.
  // If any step throws, abortTransaction() rolls back everything.

  // A session must be started on the same connection the rest of this
  // transaction's model calls will resolve to (demo or production) — see
  // startDbSession() in src/lib/db.ts.
  const session = await startDbSession();
  try {
    session.startTransaction();

    // ── 7a. Create the Bill document ──────────────────────────────────────
    // billNumber is auto-generated by the pre-save hook in bill.model.ts.
    // walletId is required by the schema.
    // status is explicitly set to CONFIRMED.
    const [bill] = await Bill.create(
      [
        {
          billNumber,
          memberId:            memberOid,
          walletId:            wallet._id,
          cardId:              card._id,
          cashierId:           actorOid,
          items:               billItems,
          totalAmount,
          walletBalanceBefore: wallet.currentBalance,
          walletBalanceAfter:  wallet.currentBalance - totalAmount,
          status:              BILL_STATUS.CONFIRMED,
          notes:               "",
          createdBy:           actorOid,
        },
      ],
      { session, ordered: true }
    );

    // ── 7b. Deduct wallet with atomic balance guard ───────────────────────
    // The { currentBalance: { $gte: totalAmount } } filter means this update
    // only succeeds if the balance is still sufficient at the exact moment
    // of the write - preventing race conditions where two bills drain the
    // same wallet simultaneously.
    const updatedWallet = await Wallet.findOneAndUpdate(
      { _id: wallet._id, currentBalance: { $gte: totalAmount } },
      { $inc: { currentBalance: -totalAmount }, updatedBy: actorOid },
      { session, new: true }
    );
    if (!updatedWallet) {
      throw new AppError(
        "Wallet balance insufficient (concurrent transaction detected).",
        400
      );
    }

    // ── 7c. Deduct stock per item with atomic qty guard ───────────────────
    // Same pattern as wallet: { currentQty: { $gte: item.quantity } } ensures
    // we never go below zero even under concurrent load.
    // Build StockMovement payloads while we have the updated quantities.
    const stockMovementDocs: object[] = [];

    for (const item of billItems) {
      const updatedStock = await Stock.findOneAndUpdate(
        {
          productId:  item.productId,
          currentQty: { $gte: item.quantity },   // ← currentQty (model field name)
        },
        { $inc: { currentQty: -item.quantity } }, // ← currentQty
        { session, new: true }
      );

      if (!updatedStock) {
        throw new AppError(
          `Insufficient stock for "${item.productName}" (concurrent update detected).`,
          400
        );
      }

      // StockMovement model field names:
      //   movementType    (not type)
      //   quantityChanged (not quantity)
      //   quantityBefore  (not balanceBefore)
      //   notes must be string, not null
      //   currentQty is the Stock field after deduction
      stockMovementDocs.push({
        productId:       item.productId,
        movementType:    STOCK_MOVEMENT_TYPES.BILLING_DEDUCTION,
        quantityChanged: item.quantity,
        quantityBefore:  updatedStock.currentQty + item.quantity, // ← before deduction
        quantityAfter:   updatedStock.currentQty,
        notes:           `Bill ${bill._id.toString().slice(-8).toUpperCase()}`,
        createdBy:       actorOid,
      });
    }

    // ── 7d. Create one Transaction record for the full bill ───────────────
    // Transaction model field names:
    //   balanceBefore (not walletBalanceBefore)
    //   balanceAfter  (not walletBalanceAfter)
    //   NO referenceId / referenceModel fields on this model
    await Transaction.create(
      [
        {
          memberId:     memberOid,
          walletId:     wallet._id,
          type:         TRANSACTION_TYPES.DEBIT,
          amount:       totalAmount,
          balanceBefore: wallet.currentBalance,
          balanceAfter:  wallet.currentBalance - totalAmount,
          createdBy:    actorOid,
        },
      ],
      { session, ordered: true }
    );

    // ── 7e. Create one StockMovement per line item ────────────────────────
    await StockMovement.create(stockMovementDocs, { session, ordered: true });

    // ── Step 8: COMMIT ─────────────────────────────────────────────────────
    // Only at this exact point do all five document types become permanently
    // written to the database simultaneously.
    await session.commitTransaction();

    return {
      id:                  bill._id.toString(),
      billNumber:          bill.billNumber,
      memberId:            memberOid.toString(),
      memberName:          member.fullName,
      cardNumber:          card.cardNumber,
      cashierId:           actorOid.toString(),
      items: billItems.map((i) => ({
        productId:   i.productId.toString(),
        productName: i.productName,
        quantity:    i.quantity,
        unitPrice:   i.unitPrice,
        subtotal:    i.subtotal,
      })),
      totalAmount,
      walletBalanceBefore: wallet.currentBalance,
      walletBalanceAfter:  wallet.currentBalance - totalAmount,
      createdAt:           bill.createdAt.toISOString(),
    };
  } catch (error) {
    await session.abortTransaction();
    throw error;
  } finally {
    // Always release the session regardless of outcome.
    session.endSession();
  }
}

// ─── listBills ────────────────────────────────────────────────────────────────
// Paginated bill history with optional member name search.
// Enriches with member name and card number via parallel $in queries.

export async function listBills(input: {
  page: number;
  limit: number;
  search: string | null;
}): Promise<{ billList: BillListRecord[]; total: number }> {
  const page  = Math.max(1, input.page);
  const limit = Math.min(Math.max(1, input.limit), 100);
  const skip  = (page - 1) * limit;

  const filter: QueryFilter<IBill> = {};

  if (input.search) {
    const safe = input.search.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const matchingMembers = await Member.find({
      isDeleted: false,
      fullName: { $regex: safe, $options: "i" },
    }).select("_id");
    filter.memberId = { $in: matchingMembers.map((m) => m._id) };
  }

  const [bills, total] = await Promise.all([
    Bill.find(filter).sort({ createdAt: -1 }).skip(skip).limit(limit),
    Bill.countDocuments(filter),
  ]);

  if (bills.length === 0) return { billList: [], total };

  const memberIds = bills.map((b) => b.memberId);
  const cardIds   = bills.map((b) => b.cardId);

  const [members, cards] = await Promise.all([
    Member.find({ _id: { $in: memberIds } }),
    Card.find({ _id: { $in: cardIds } }),
  ]);

  const memberMap = new Map(members.map((m) => [m._id.toString(), m.fullName]));
  const cardMap   = new Map(cards.map((c) => [c._id.toString(), c.cardNumber]));

  const billList: BillListRecord[] = bills.map((b) => ({
    id:                  b._id.toString(),
    billNumber:          b.billNumber,
    memberName:          memberMap.get(b.memberId.toString()) ?? "Unknown",
    cardNumber:          cardMap.get(b.cardId.toString())     ?? "Unknown",
    totalAmount:         b.totalAmount,
    itemCount:           b.items.length,
    walletBalanceBefore: b.walletBalanceBefore,
    walletBalanceAfter:  b.walletBalanceAfter,
    createdAt:           b.createdAt.toISOString(),
  }));

  return { billList, total };
}

// ─── getBillDetail ────────────────────────────────────────────────────────────
// Fetches one bill with all line items, member name, and card number.

export async function getBillDetail(billId: string): Promise<BillRecord> {
  if (!mongoose.Types.ObjectId.isValid(billId)) {
    throw new AppError("Invalid bill ID.", 400);
  }

  const bill = await Bill.findById(billId);
  if (!bill) throw new AppError("Bill not found.", 404);

  const [member, card] = await Promise.all([
    Member.findById(bill.memberId),
    Card.findById(bill.cardId),
  ]);

  return {
    id:                  bill._id.toString(),
    billNumber:          bill.billNumber,
    memberId:            bill.memberId.toString(),
    memberName:          member?.fullName  ?? "Unknown",
    cardNumber:          card?.cardNumber  ?? "Unknown",
    cashierId:           bill.cashierId.toString(),
    items: bill.items.map((i: {
      productId:   mongoose.Types.ObjectId;
      productName: string;
      quantity:    number;
      unitPrice:   number;
      subtotal:    number;
    }) => ({
      productId:   i.productId.toString(),
      productName: i.productName,
      quantity:    i.quantity,
      unitPrice:   i.unitPrice,
      subtotal:    i.subtotal,
    })),
    totalAmount:         bill.totalAmount,
    walletBalanceBefore: bill.walletBalanceBefore,
    walletBalanceAfter:  bill.walletBalanceAfter,
    createdAt:           bill.createdAt.toISOString(),
  };
}
